/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        }
    ],
    "debugbar.queries.explain": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "dashboard": [],
    "release-notes.index": [],
    "profile.edit": [],
    "profile.update": [],
    "branches.index": [],
    "branches.create": [],
    "branches.store": [],
    "branches.show": [
        {
            "name": "branch",
            "required": true
        }
    ],
    "branches.edit": [
        {
            "name": "branch",
            "required": true
        }
    ],
    "branches.update": [
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "branches.destroy": [
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "tags.index": [],
    "tags.create": [],
    "tags.store": [],
    "tags.show": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "tags.edit": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "tags.update": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "tags.destroy": [
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.update-status": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.update-staff": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.update-duedate": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.duplicate": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.tags.add": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.tags.remove": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        },
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.tags.update-quantity": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        },
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.images.index": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.images.store": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.images.destroy": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        },
        {
            "name": "image",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.index": [],
    "sublimations.create": [],
    "sublimations.store": [],
    "sublimations.show": [
        {
            "name": "sublimation",
            "required": true
        }
    ],
    "sublimations.edit": [
        {
            "name": "sublimation",
            "required": true
        }
    ],
    "sublimations.update": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        }
    ],
    "sublimations.destroy": [
        {
            "name": "sublimation",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.index": [],
    "customers.create": [],
    "customers.store": [],
    "customers.show": [
        {
            "name": "customer",
            "required": true
        }
    ],
    "customers.edit": [
        {
            "name": "customer",
            "required": true
        }
    ],
    "customers.update": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.destroy": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.print": [],
    "sales.update-payment": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.refund-payment": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.attachment.store": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.attachment.destroy": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.index": [],
    "sales.store": [],
    "sales.update": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.destroy": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.status.update": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.transactions.store": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.update-staff": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "purchase-orders.index": [],
    "purchase-orders.create": [],
    "purchase-orders.store": [],
    "purchase-orders.show": [
        {
            "name": "purchase_order",
            "required": true
        }
    ],
    "purchase-orders.edit": [
        {
            "name": "purchase_order",
            "required": true
        }
    ],
    "purchase-orders.update": [
        {
            "name": "purchase_order",
            "required": true
        }
    ],
    "purchase-orders.destroy": [
        {
            "name": "purchase_order",
            "required": true
        }
    ],
    "endorsements.index": [],
    "endorsements.create": [],
    "endorsements.store": [],
    "endorsements.show": [
        {
            "name": "endorsement",
            "required": true
        }
    ],
    "endorsements.edit": [
        {
            "name": "endorsement",
            "required": true
        }
    ],
    "endorsements.update": [
        {
            "name": "endorsement",
            "required": true,
            "binding": "id"
        }
    ],
    "endorsements.destroy": [
        {
            "name": "endorsement",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.print": [],
    "expenses.void": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.approve": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.reject": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.index": [],
    "expenses.create": [],
    "expenses.store": [],
    "expenses.show": [
        {
            "name": "expense",
            "required": true
        }
    ],
    "expenses.edit": [
        {
            "name": "expense",
            "required": true
        }
    ],
    "expenses.update": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.destroy": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "incentives.index": [],
    "incentives.pay": [],
    "payroll.index": [],
    "payroll.employees.index": [],
    "payroll.employees.create": [],
    "payroll.employees.store": [],
    "payroll.employees.show": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.edit": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.update": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.deactivate": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.rehire": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.link-user": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.unlink-user": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.sync-user": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.sync-all": [],
    "payroll.audit.index": [],
    "payroll.attendance.index": [],
    "payroll.attendance.punch": [],
    "payroll.attendance.manual": [],
    "payroll.employee.profile.update": [],
    "payroll.holidays.index": [],
    "payroll.holidays.store": [],
    "payroll.holidays.update": [
        {
            "name": "holiday",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.holidays.destroy": [
        {
            "name": "holiday",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.schedules.store": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.schedules.update": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.employees.schedules.destroy": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.attendance.sheets.index": [],
    "payroll.attendance.sheets.show": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.attendance.logs.store": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.attendance.logs.destroy": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        },
        {
            "name": "log",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.attendance.geo": [],
    "payroll.fines.store": [],
    "payroll.fines.destroy": [
        {
            "name": "fine",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.periods.index": [],
    "payroll.periods.generate": [],
    "payroll.periods.show": [
        {
            "name": "period",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.periods.check": [
        {
            "name": "period",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.periods.recompute": [
        {
            "name": "period",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.periods.approve": [
        {
            "name": "period",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.periods.void": [
        {
            "name": "period",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.periods.destroy": [
        {
            "name": "period",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.payslip": [
        {
            "name": "period",
            "required": true,
            "binding": "id"
        },
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.my-payslip": [],
    "payroll.work-week.index": [],
    "payroll.work-week.print": [],
    "payroll.reports.index": [],
    "payroll.reports.print": [],
    "payroll.reports.branch-payables": [],
    "payroll.sss.brackets.index": [],
    "payroll.sss.brackets.store": [],
    "payroll.sss.brackets.update": [
        {
            "name": "bracket",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.sss.brackets.destroy": [
        {
            "name": "bracket",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.company.config.index": [],
    "payroll.company.config.update": [],
    "payroll.overtime.index": [],
    "payroll.overtime.store": [],
    "payroll.overtime.approve": [
        {
            "name": "overtimeRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.overtime.deny": [
        {
            "name": "overtimeRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.leaves.index": [],
    "payroll.leaves.store": [],
    "payroll.leaves.approve": [
        {
            "name": "leaveRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.leaves.deny": [
        {
            "name": "leaveRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.leaves.cancel": [
        {
            "name": "leaveRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.leaves.reset": [],
    "payroll.corrections.index": [],
    "payroll.corrections.store": [],
    "payroll.corrections.approve": [
        {
            "name": "correction",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.corrections.deny": [
        {
            "name": "correction",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.cash-advances.index": [],
    "payroll.cash-advances.store": [],
    "payroll.cash-advances.approve": [
        {
            "name": "cashAdvance",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.cash-advances.deny": [
        {
            "name": "cashAdvance",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.sewed-items.index": [],
    "payroll.sewed-items.payslip": [],
    "payroll.sewed-items.payslip.approve": [
        {
            "name": "payslip",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.sewed-items.payslip.cancel": [
        {
            "name": "payslip",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.sewed-items.store": [],
    "payroll.sewed-items.update": [
        {
            "name": "sewedItem",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.sewed-items.destroy": [
        {
            "name": "sewedItem",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.settings.index": [],
    "payroll.settings.update": [],
    "payroll.admin.fix-no-break-fine": [],
    "payroll.admin.recalculate-late-deductions": [],
    "api.customers.index": [],
    "profile.destroy": [],
    "security.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
